server:
  port: 8130
spring:
  application:
    name: spring-admin
  boot:
    admin:
      client:
        url: http://localhost:8120
  cloud:
    config:
      server:
        git:
          uri: file:///D:/Projects/Java/spring-cloud-practice/spring-config-repo
          searchPaths: '{application}'
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8110/eureka